name: "Lesson 2 - Exercise 3"

on:
    workflow_dispatch:

jobs:
    test:
      runs-on: ubuntu-latest
      env:
        MAXIMUM_ATTEMPTS: ${{vars.MAXIMUM_ATTEMPTS}}
      steps:
        - name: Prevent reruns
          run: |
            # Exit if the run number is greater than the maximum number of attempts
            if [ $GITHUB_RUN_ATTEMPT -gt $MAXIMUM_ATTEMPTS ]; then
              echo "Exiting because the run number is greater than the maximum number of attempts"
              exit 1
            fi
          # Add your solution below this line
          # Hint: read more about the github context here: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          # Hint: read more about setting job level environment variables here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenv

        - name: Run job
          run: |
            echo "Running job"
            sleep 1
